env:
  browser: true
  es6: true
  node: true
extends:
  - eslint:recommended
  - google
  - plugin:vue/recommended
parserOptions:
  ecmaVersion: 2021
  sourceType: module
plugins:
  - vue
root: true
rules:
  arrow-parens:
    - error
    - always
  max-len: 0  # See vue/max-len below
  object-curly-spacing:
    - error
    - always
    - objectsInObjects: false
  require-jsdoc: 0
  vue/max-len:
    - error
    - code: 80
      template: 120
