# Site settings
title: Fiddle
url: "http://fiddle.liamnewmarch.co.uk"
twitter_username: liamnewmarch
github_username: liamnewmarch

# Build settings
markdown: kramdown
exclude:
- CNAME
sass:
  sass_dir: assets/css
  style: compressed
