steps:
  - name: node:16-alpine
    args:
      - npm
      - clean-install
  - name: node:16-alpine
    args:
      - npm
      - test
  - name: node:16-alpine
    args:
      - npm
      - run
      - build
  - name: node:16-alpine
    args:
      - npm
      - run
      - deploy
