import js from "@eslint/js"
import globals from "globals"
import pluginVue from "eslint-plugin-vue"
import pluginImport from "eslint-plugin-import"
import tseslint from "typescript-eslint"

export default [
  js.configs.recommended,
  ...pluginVue.configs["flat/recommended"],
  {
    files: ["**/*.ts"],
    plugins: { "@typescript-eslint": tseslint.plugin },
    languageOptions: { parser: tseslint.parser },
    rules: {
      "@typescript-eslint/no-non-null-assertion": "error",
      "@typescript-eslint/no-explicit-any": "error",
      "@typescript-eslint/consistent-type-assertions": ["error", { assertionStyle: "never" }],
      "no-restricted-syntax": ["error", {
        selector: "TSUndefinedKeyword",
        message: "Use optional `?` or `void` instead of `undefined` in types",
      }],
    },
  },
  {
    files: ["**/*.vue"],
    plugins: { "@typescript-eslint": tseslint.plugin },
    languageOptions: { parserOptions: { parser: tseslint.parser }},
    rules: {
      "@typescript-eslint/no-non-null-assertion": "error",
      "@typescript-eslint/no-explicit-any": "error",
      "@typescript-eslint/consistent-type-assertions": ["error", { assertionStyle: "never" }],
      "no-restricted-syntax": ["error", {
        selector: "TSUndefinedKeyword",
        message: "Use optional `?` or `void` instead of `undefined` in types",
      }],
    },
  },
  {
    languageOptions: {
      globals: {
        ...globals.browser,
        VERSION: "readonly",
      },
    },
    plugins: {
      import: pluginImport,
    },
    rules: {
      "curly": [2, "multi-line"],
      "guard-for-in": 2,
      "no-caller": 2,
      "no-extend-native": 2,
      "no-extra-bind": 2,
      "no-invalid-this": 2,
      "no-multi-spaces": 2,
      "no-multi-str": 2,
      "no-new-wrappers": 2,
      "no-throw-literal": 2,
      "prefer-promise-reject-errors": 2,
      "no-unused-vars": [2, { args: "none" }],
      "array-bracket-spacing": [2, "never"],
      "block-spacing": [2, "never"],
      "brace-style": 2,
      "camelcase": [2, { properties: "never" }],
      "comma-dangle": [2, "always-multiline"],
      "comma-spacing": 2,
      "comma-style": 2,
      "computed-property-spacing": 2,
      "eol-last": 2,
      "func-call-spacing": 2,
      "generator-star-spacing": [2, "after"],
      "indent": [2, 2, {
        "CallExpression": { "arguments": 2 },
        "FunctionDeclaration": { "body": 1, "parameters": 2 },
        "FunctionExpression": { "body": 1, "parameters": 2 },
        "MemberExpression": 2,
        "ObjectExpression": 1,
        "SwitchCase": 1,
        "ignoredNodes": ["ConditionalExpression"],
      }],
      "key-spacing": 2,
      "keyword-spacing": 2,
      "linebreak-style": 2,
      "new-cap": 2,
      "no-array-constructor": 2,
      "no-multiple-empty-lines": [2, { max: 2 }],
      "no-new-object": 2,
      "no-tabs": 2,
      "no-trailing-spaces": 2,
      "one-var": [2, { var: "never", let: "never", const: "never" }],
      "operator-linebreak": [2, "after"],
      "padded-blocks": [2, "never"],
      "quote-props": [2, "consistent"],
      "quotes": [2, "double", { allowTemplateLiterals: true }],
      "rest-spread-spacing": 2,
      "semi": [2, "never"],
      "semi-spacing": 2,
      "space-before-blocks": 2,
      "space-before-function-paren": [2, {
        asyncArrow: "always",
        anonymous: "never",
        named: "never",
      }],
      // "sort-keys": 2, // TODO
      "spaced-comment": [2, "always"],
      "switch-colon-spacing": 2,
      "yield-star-spacing": [2, "after"],
      "prefer-rest-params": 2,
      "prefer-spread": 2,
      "arrow-parens": ["error", "always"],
      "max-len": 0,
      "no-undefined": "error",
      "no-var": "error",
      "object-curly-spacing": ["error", "always", { objectsInObjects: false }],
      "prefer-const": ["error", { destructuring: "all" }],
      "require-jsdoc": 0,
      "vue/max-len": ["error", { code: 120, ignoreUrls: true }],
    },
  },
  {
    ignores: ["dist/**", "public/**", "src/env.d.ts"],
  },
]
